User profile page
TuiChain/frontend pull request #100
Opened 2021-01-25 17:52 UTC by Tiagod25

2021-01-25 18:10 UTC, pferreira101 commented on web/src/containers/students/Student.js
> +              {matches === false && (
Use a ternary expression, matches? (<Box>....</Box>) : (<Box>....</Box>)

2021-01-25 19:06 UTC, Tiagod25 commented on web/src/containers/students/Student.js
> +              {matches === false && (
done

2021-01-26 00:43 UTC, Bishop19 commented on web/src/containers/UserProfile.js
> +  };
this function should be defined inside Formik (marked bellow)

2021-01-26 00:52 UTC, Bishop19 commented on web/src/containers/UserProfile.js
> +    onSubmit: async (values, { setFieldValue }) => {
here

2021-01-26 00:54 UTC, Bishop19 requested changes

2021-01-26 00:54 UTC, Bishop19 commented on web/src/containers/UserProfile.js
> +  useEffect(async () => {
Is this working? useEffect can't handle async function as argument i guess (cf. other useEffects)

2021-01-26 19:34 UTC, Bishop19 approved these changes

2021-01-26 20:30 UTC, joaop21 approved these changes

2021-01-26 21:27 UTC, merged