Add toast to photo submit button
TuiChain/frontend pull request #125
Opened 2021-01-28 23:52 UTC by pferreira101

Resolves #124

2021-01-29 00:26 UTC, joaop21 approved these changes

2021-01-29 12:15 UTC, Bishop19 requested changes

2021-01-29 12:15 UTC, Bishop19 commented on web/src/containers/UserProfile.js
> +    setOpen(true);
e se falhar?

2021-01-29 14:06 UTC, pferreira101 commented on web/src/containers/UserProfile.js
> +    setOpen(true);
Não sei em que cenários é que falha, até sem foto selecionada faz o upload... Mas posso ver isso

2021-01-29 15:03 UTC, Bishop19 commented on web/src/containers/UserProfile.js
> +    setOpen(true);
vê também a atualiuzação do perfil em cima sff
é so ver se o serviço falha ou não acho eu

2021-01-29 17:50 UTC, Tiagod25 approved these changes

2021-01-30 14:20 UTC, Bishop19 approved these changes

2021-01-30 15:48 UTC, merged