Kyc button
TuiChain/frontend pull request #41
Opened 2021-01-13 16:12 UTC by nelsontss

2021-01-14 23:15 UTC, Bishop19 requested changes

2021-01-14 23:15 UTC, Bishop19 commented on web/src/App.js
> +              />
Remember to remove this

2021-01-14 23:15 UTC, Bishop19 commented on web/src/containers/KycButton.js
> +
run prettier

2021-01-14 23:15 UTC, Bishop19 commented on web/src/services/kyc.service.js
> +      // TODO : why is error overwritten in browser? we need to catch a specific error
aquele copy paste

2021-01-15 18:29 UTC, Tiagod25 approved these changes

2021-01-16 13:07 UTC, Bishop19 approved these changes

2021-01-16 13:07 UTC, Bishop19 commented on web/src/services/investment.service.js
>      console.log(response);
return true on success and false on error?

2021-01-16 13:42 UTC, merged