Add CircularProgress animation
TuiChain/frontend pull request #56
Opened 2021-01-16 02:08 UTC by pferreira101

Closes #54 

This PR adds a CircularProgress animation to submission buttons on forms: while the form data is being submitted the button text is replaced by the animation.

It also adds the LoadingPageAnimation component, intended to be used in pages where data is fetched from the backend. It was already applied to the Student page.

2021-01-16 12:48 UTC, Bishop19 requested changes

2021-01-16 12:48 UTC, Bishop19 commented on web/src/containers/students/Student.js
> +      {isEmpty(user) || isEmpty(userInfo) ? (
a condição não deveria ser algo "isFetching" e caso a resposta do serviço seja 'false' (por não haver o student com o id indicado no url, por exemplo) dar redirect para a 404. Object.keys(false).length também dá 0, pelo que no caso anterior estaria sempre loading apesar do pedido já ter sido efetuado

2021-01-16 18:49 UTC, pferreira101 commented on web/src/containers/students/Student.js
> +      {isEmpty(user) || isEmpty(userInfo) ? (
Alterei a verificação para fazer uso de uma var booleana que indica se os dados estão a ser fetched ou não.

2021-01-17 18:07 UTC, joaop21 approved these changes

2021-01-17 18:08 UTC, Bishop19 approved these changes

2021-01-17 19:53 UTC, merged