Admin finalize loans
TuiChain/frontend pull request #93
Opened 2021-01-24 21:33 UTC by Bishop19

This PR closes #76

2021-01-25 19:17 UTC, pferreira101 approved these changes

2021-01-25 23:04 UTC, joaop21 requested changes

2021-01-25 23:04 UTC, joaop21 commented on web/src/services/loans.service.js
> +};
cancel and withdrawn were throwing errors for ManageLoan to catch, and work with them

2021-01-26 00:11 UTC, joaop21 approved these changes

2021-01-26 00:31 UTC, merged