Loan states
TuiChain/frontend pull request #98
Opened 2021-01-25 02:02 UTC by joaop21

Give me your opinion in what each state should show.
Or if it is just fine, tell me as well.

Resolves: #85 

https://user-images.githubusercontent.com/36553777/105652477-45e83400-5eb1-11eb-9908-d9facda9ff86.mov

2021-01-25 02:48 UTC, Bishop19 requested changes

2021-01-25 02:48 UTC, Bishop19 commented on web/src/containers/loans/Loan.js
> +    ) {
treat each state as a component, cf. LoanActive. Cleaner code as it has no conditionals

2021-01-25 02:48 UTC, Bishop19 commented on web/src/containers/loans/Loan.js
> +        )}
this would be cleaner with a ternary operator. still, i think it would be better to say that there are no documents in the card below

2021-01-26 00:38 UTC, Bishop19 commented on web/src/containers/loans/Loan.js
> +};
The pattern used is to define these type of functions inside the useEffect. This way you don't have to pass functions outside of the component

2021-01-26 00:40 UTC, Bishop19 approved these changes

2021-01-26 14:56 UTC, Bishop19 approved these changes

2021-01-26 18:26 UTC, Tiagod25 approved these changes

2021-01-26 18:43 UTC, pferreira101 approved these changes

2021-01-26 18:56 UTC, merged